### ISSUE TITLE
fix_using_gpu_in_docker

### ISSUE THREAD

**Issue by yastcher** [yastcher/visitors-observer#13]
Uncomment in docker-compose.yaml and using nvidia/cuda in Dockerfile
```
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

```

Fix error in using nvidia/cuda image from:

https://hub.docker.com/r/nvidia/cuda/tags

numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform
